/**
 * PrivatePay ZK — Client-Side ZK Proof Library (v2)
 *
 * This module handles all zero-knowledge proof operations in the browser.
 *
 * It relies on circuit artifacts generated by:
 *   cd circuits && npm run build:all
 *
 * Expected files in /public/circuits/<name>/:
 *   - <name>.wasm                       (compiled witness calculator)
 *   - <name>_final.zkey                 (Groth16 proving key)
 *   - <name>_verification_key.json      (for local pre-verification)
 */

// ── Types ─────────────────────────────────────────────────────────────────────

export interface ZKNote {
  /** Random BN254 field element — never share */
  secret: string;
  /** Random BN254 field element — never share */
  nullifier: string;
  /** Poseidon(secret, nullifier) — submit on-chain during deposit */
  commitment: string;
  /** Poseidon(nullifier) — included in withdraw proof as public input */
  nullifierHash: string;
  /** Timestamp for record keeping */
  createdAt: number;
}

export interface MerklePathInput {
  /** Sibling hashes along the path from leaf to root */
  pathElements: string[];
  /** 0 = left child, 1 = right child, at each level */
  pathIndices: number[];
  /** The Merkle root (fetched from the on-chain pool contract) */
  root: string;
}

export interface WithdrawCircuitInputs {
  root: string;
  nullifierHash: string;
  secret: string;
  nullifier: string;
  pathElements: string[];
  pathIndices: number[];
}

export interface ComplianceCircuitInputs extends WithdrawCircuitInputs {
  auditorPubKey: string;
  encryptedData: string;
  amount: string;
  senderId: string;
  recipientId: string;
}

export interface Groth16Proof {
  pi_a: [string, string, string];
  pi_b: [[string, string], [string, string], [string, string]];
  pi_c: [string, string, string];
  protocol: string;
  curve: string;
}

export interface ProofResult {
  proof: Groth16Proof;
  publicSignals: string[];
  /** Time in milliseconds to generate the proof */
  proofTimeMs: number;
}

/** Byte encoding for the Soroban contract's verify() call */
export interface SorobanVerifyArgs {
  /** 64-byte big-endian G1 point (x || y) */
  proof_a: Uint8Array;
  /** 128-byte big-endian G2 point (x_c1 || x_c0 || y_c1 || y_c0) */
  proof_b: Uint8Array;
  /** 64-byte big-endian G1 point (x || y) */
  proof_c: Uint8Array;
  /** Array of 32-byte big-endian public input scalars */
  public_inputs: Uint8Array[];
}

// ── BN254 Field ───────────────────────────────────────────────────────────────

const BN254_P = BigInt(
  "21888242871839275222246405745257275088548364400416034343698204186575808495617"
);

// ── Cryptographically Secure Random Field Element ─────────────────────────────

/**
 * Generate a 31-byte cryptographically secure random BN254 field element.
 * Using 31 bytes ensures we stay below the field modulus without rejection sampling.
 */
export function randomFieldElement(): string {
  const bytes = new Uint8Array(31);
  crypto.getRandomValues(bytes);
  const hex = Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
  return (BigInt("0x" + hex) % BN254_P).toString();
}

// ── Poseidon Hash (via circomlibjs) ──────────────────────────────────────────

type PoseidonFn = (inputs: bigint[]) => bigint;
let _poseidon: PoseidonFn | null = null;

async function poseidon(inputs: (string | bigint)[]): Promise<bigint> {
  if (!_poseidon) {
    const { buildPoseidon } = await import("circomlibjs");
    const pos = await buildPoseidon();
    _poseidon = (ins: bigint[]) => {
      const r = pos(ins);
      return pos.F.toObject(r) as bigint;
    };
  }
  return _poseidon(inputs.map(BigInt));
}

// ── Commitment Generation ─────────────────────────────────────────────────────

/**
 * Generate a new ZK commitment note for a deposit.
 *
 * The user MUST store the returned note securely — it is required for withdrawal.
 * If lost, the deposited funds are unrecoverable.
 */
export async function generateNote(): Promise<ZKNote> {
  const secret   = randomFieldElement();
  const nullifier = randomFieldElement();

  const commitment    = await poseidon([secret, nullifier]);
  const nullifierHash = await poseidon([nullifier]);

  return {
    secret,
    nullifier,
    commitment:    "0x" + commitment.toString(16).padStart(64, "0"),
    nullifierHash: "0x" + nullifierHash.toString(16).padStart(64, "0"),
    createdAt:     Date.now(),
  };
}

/**
 * Re-derive commitment and nullifier hash from secret and nullifier keys.
 */
export async function computeNoteCommitmentAndNullifier(
  secret: string,
  nullifier: string
): Promise<{ commitment: string; nullifierHash: string }> {
  const comm = await poseidon([secret, nullifier]);
  const nh = await poseidon([nullifier]);
  return {
    commitment: "0x" + comm.toString(16).padStart(64, "0"),
    nullifierHash: "0x" + nh.toString(16).padStart(64, "0"),
  };
}

// ── Merkle Tree (Client-side, mirrors Soroban contract) ───────────────────────

const ZERO = BigInt(0);

/**
 * Compute the Merkle root of a list of commitment leaves using Poseidon.
 * Mirrors the on-chain Poseidon Merkle tree in the pool contract.
 */
export async function computeMerkleRoot(
  leaves: bigint[],
  depth: number = 4
): Promise<bigint> {
  // Pad to 2^depth
  const padded = [...leaves];
  while (padded.length < Math.pow(2, depth)) padded.push(ZERO);

  let level = padded;
  for (let d = 0; d < depth; d++) {
    const next: bigint[] = [];
    for (let i = 0; i < level.length; i += 2) {
      next.push(await poseidon([level[i], level[i + 1]]));
    }
    level = next;
  }
  return level[0];
}

/**
 * Compute the Merkle path (sibling elements + indices) for a leaf at a given index.
 */
export async function getMerklePath(
  leaves: bigint[],
  leafIndex: number,
  depth: number = 4
): Promise<MerklePathInput> {
  const padded = [...leaves];
  while (padded.length < Math.pow(2, depth)) padded.push(ZERO);

  // Build all levels
  const levels: bigint[][] = [padded];
  let current = padded;
  for (let d = 0; d < depth; d++) {
    const next: bigint[] = [];
    for (let i = 0; i < current.length; i += 2) {
      next.push(await poseidon([current[i], current[i + 1]]));
    }
    levels.push(next);
    current = next;
  }

  const pathElements: string[] = [];
  const pathIndices: number[] = [];
  let idx = leafIndex;

  for (let d = 0; d < depth; d++) {
    const siblingIdx = idx % 2 === 0 ? idx + 1 : idx - 1;
    pathElements.push((levels[d][siblingIdx] ?? ZERO).toString());
    pathIndices.push(idx % 2);
    idx = Math.floor(idx / 2);
  }

  return {
    pathElements,
    pathIndices,
    root: levels[depth][0].toString(),
  };
}

// ── Proof Generation ─────────────────────────────────────────────────────────

/**
 * Generate a Groth16 withdrawal proof.
 *
 * Requires compiled circuit artifacts in /public/circuits/withdraw/:
 *   withdraw.wasm + withdraw_final.zkey
 *
 * @param inputs - Circuit private + public inputs
 * @returns The proof, public signals, and timing data
 */
export async function proveWithdraw(
  inputs: WithdrawCircuitInputs
): Promise<ProofResult> {
  const snarkjs = await import("snarkjs");
  const start   = performance.now();

  const { proof, publicSignals } = await snarkjs.groth16.fullProve(
    inputs,
    "/circuits/withdraw/withdraw.wasm",
    "/circuits/withdraw/withdraw_final.zkey"
  );

  return {
    proof: proof as Groth16Proof,
    publicSignals,
    proofTimeMs: Math.round(performance.now() - start),
  };
}

/**
 * Generate a Groth16 compliance (selective disclosure) proof.
 */
export async function proveCompliance(
  inputs: ComplianceCircuitInputs
): Promise<ProofResult> {
  const snarkjs = await import("snarkjs");
  const start   = performance.now();

  const { proof, publicSignals } = await snarkjs.groth16.fullProve(
    inputs,
    "/circuits/compliance/compliance.wasm",
    "/circuits/compliance/compliance_final.zkey"
  );

  return {
    proof: proof as Groth16Proof,
    publicSignals,
    proofTimeMs: Math.round(performance.now() - start),
  };
}

/**
 * Verify a proof locally using the verification key JSON.
 * Performs the same check the Soroban contract does, but in the browser.
 * Use as a pre-submission sanity check to avoid failed on-chain transactions.
 */
export async function verifyLocally(
  circuitName: "withdraw" | "compliance",
  proof: Groth16Proof,
  publicSignals: string[]
): Promise<boolean> {
  const snarkjs = await import("snarkjs");
  const res     = await fetch(`/circuits/${circuitName}/${circuitName}_verification_key.json`);
  if (!res.ok) throw new Error(`Could not load vkey for ${circuitName}`);
  const vKey = await res.json();
  return snarkjs.groth16.verify(vKey, publicSignals, proof);
}

// ── Soroban Encoding ──────────────────────────────────────────────────────────

function bn254ToBytes32(n: string | bigint): Uint8Array {
  const hex = BigInt(n).toString(16).padStart(64, "0");
  return new Uint8Array(32).map((_, i) => parseInt(hex.slice(i * 2, i * 2 + 2), 16));
}

/**
 * Serialize a Groth16 proof into the exact byte encoding expected by
 * the Soroban Groth16VerifierContract.verify() function.
 *
 * The BN254 point encoding convention:
 *   G1: [x_be_32 | y_be_32]                            = 64 bytes
 *   G2: [x_c1_be_32 | x_c0_be_32 | y_c1_be_32 | y_c0_be_32] = 128 bytes
 *
 * snarkjs uses (c0, c1) order for G2 coordinates; Soroban expects (c1, c0).
 * This function handles the swap.
 */
export function encodeForSoroban(
  proof: Groth16Proof,
  publicSignals: string[]
): SorobanVerifyArgs {
  const g1 = (x: string, y: string): Uint8Array => {
    const buf = new Uint8Array(64);
    buf.set(bn254ToBytes32(x), 0);
    buf.set(bn254ToBytes32(y), 32);
    return buf;
  };

  // snarkjs pi_b[i] = [c0, c1]; Soroban expects [c1, c0]
  const g2 = (xc0: string, xc1: string, yc0: string, yc1: string): Uint8Array => {
    const buf = new Uint8Array(128);
    buf.set(bn254ToBytes32(xc1), 0);   // x_c1
    buf.set(bn254ToBytes32(xc0), 32);  // x_c0
    buf.set(bn254ToBytes32(yc1), 64);  // y_c1
    buf.set(bn254ToBytes32(yc0), 96);  // y_c0
    return buf;
  };

  return {
    proof_a: g1(proof.pi_a[0], proof.pi_a[1]),
    proof_b: g2(
      proof.pi_b[0][0], proof.pi_b[0][1],
      proof.pi_b[1][0], proof.pi_b[1][1]
    ),
    proof_c: g1(proof.pi_c[0], proof.pi_c[1]),
    public_inputs: publicSignals.map(bn254ToBytes32),
  };
}

/**
 * Compute Poseidon hash of inputs (returns decimal string).
 */
export async function computePoseidonHash(inputs: string[]): Promise<string> {
  const hash = await poseidon(inputs);
  return hash.toString();
}
